server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5435/ai_service_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

openrouter:
  base-url: https://openrouter.ai/api/v1
  model: huggingfaceh4/zephyr-7b-beta
  timeout: 120
  keys:
    portfolio: ${OPENROUTER_KEY_PORTFOLIO:}
    market: ${OPENROUTER_KEY_MARKET:}
    news: ${OPENROUTER_KEY_NEWS:}
    stock: ${OPENROUTER_KEY_STOCK:}
    strategy: ${OPENROUTER_KEY_STRATEGY:}
    analyst: ${OPENROUTER_KEY_ANALYST:}
    report: ${OPENROUTER_KEY_REPORT:}

# Analysis Configuration
analysis:
  target-monthly-income: 100000
  default-years-horizon: 15

logging:
  level:
    root: INFO
    ru.javabegin: DEBUG
  file:
    name: logs/ai-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
