server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5435/ai_service_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:news_cache}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin123}
      authentication-database: admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ai-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

gemini:
  base-url: https://generativelanguage.googleapis.com/v1beta/models
  default-model: gemini-2.5-flash-lite
  timeout: 1200
  models:
    - name: flash-lite
      model-id: gemini-2.5-flash-lite
      requests-per-minute: 15
      requests-per-day: 1500
    - name: flash
      model-id: gemini-2.5-flash
      requests-per-minute: 15
      requests-per-day: 1500
    - name: pro
      model-id: gemini-2.5-pro
      requests-per-minute: 5
      requests-per-day: 50
  api-keys:
    portfolio: ${GEMINI_API_KEY:}
    market: ${GEMINI_API_KEY:}
    news: ${GEMINI_API_KEY:}
    stock: ${GEMINI_API_KEY:}
    strategy: ${GEMINI_API_KEY:}
    analyst: ${GEMINI_API_KEY:}
    report: ${GEMINI_API_KEY:}

# Analysis Configuration
analysis:
  target-monthly-income: 100000
  default-years-horizon: 15

# FlareSolverr Configuration
flaresolverr:
  base-url: http://localhost:8191
  max-timeout: 60000
  cache-ttl-hours: 6
  max-news-per-source: 10

logging:
  level:
    root: INFO
    ru.javabegin: DEBUG
  file:
    name: logs/ai-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
