server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5435/ai_service_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:news_cache}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:admin123}
      authentication-database: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

gemini:
  base-url: https://generativelanguage.googleapis.com/v1beta/models
  default-model: gemini-1.5-flash
  timeout: 120
  models:
    - name: flash
      model-id: gemini-1.5-flash
      requests-per-minute: 15
      requests-per-day: 1500
    - name: flash-8b
      model-id: gemini-1.5-flash-8b
      requests-per-minute: 15
      requests-per-day: 1500
    - name: pro
      model-id: gemini-1.5-pro
      requests-per-minute: 2
      requests-per-day: 50
  api-keys:
    portfolio: ${GEMINI_API_KEY_PORTFOLIO:}
    market: ${GEMINI_API_KEY_MARKET:}
    news: ${GEMINI_API_KEY_NEWS:}
    stock: ${GEMINI_API_KEY_STOCK:}
    strategy: ${GEMINI_API_KEY_STRATEGY:}
    analyst: ${GEMINI_API_KEY_ANALYST:}
    report: ${GEMINI_API_KEY_REPORT:}

# Analysis Configuration
analysis:
  target-monthly-income: 100000
  default-years-horizon: 15

# FlareSolverr Configuration
flaresolverr:
  base-url: http://localhost:8191
  max-timeout: 60000
  cache-ttl-hours: 6
  max-news-per-source: 10

logging:
  level:
    root: INFO
    ru.javabegin: DEBUG
  file:
    name: logs/ai-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
