server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: telegram-bot-service
  datasource:
    url: jdbc:postgresql://localhost:5434/bot_state_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

# Feign Client Configuration - увеличенные таймауты для AI анализа
feign:
  client:
    config:
      default:
        connectTimeout: 10000      # 10 секунд на подключение
        readTimeout: 180000        # 3 минуты на чтение ответа (AI анализ долгий)
      ai-service:
        connectTimeout: 10000
        readTimeout: 180000        # 3 минуты специально для AI Service

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:your-bot-token-here}
    username: ${TELEGRAM_BOT_USERNAME:your-bot-username}

logging:
  level:
    root: INFO
    ru.javabegin: DEBUG
  file:
    name: logs/telegram-bot-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

elasticsearch:
  host: localhost
  port: 9200
