server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: telegram-bot-service
  datasource:
    url: jdbc:postgresql://localhost:5434/bot_state_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:your-bot-token-here}
    username: ${TELEGRAM_BOT_USERNAME:your-bot-username}
