server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: tinkoff-integration-service
  datasource:
    url: jdbc:postgresql://localhost:5433/tinkoff_cache_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

tinkoff:
  api:
    token: ${TINKOFF_API_TOKEN:your-token-here}
  cache:
    ttl-minutes: 5
