server:
  port: 0  # Динамическое присваивание порта

spring:
  application:
    name: tinkoff-integration-service
  datasource:
    url: jdbc:postgresql://localhost:5433/tinkoff_cache_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

tinkoff:
  cache:
    ttl-minutes: 5

logging:
  level:
    root: INFO
    ru.javabegin: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  file:
    name: logs/tinkoff-integration-service.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

elasticsearch:
  host: localhost
  port: 9200
